[package]
name = "chunnel"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[dependencies]
dbus = "0.6"
getopts = "0.2"
libc = "0.2"
libchromeos = { path = "../../libchromeos-rs" } # provided by ebuild
log = "0.4"
protobuf = "2"
remain = "0.1"
sys_util = { path = "../../../platform/crosvm/sys_util" } # provided by ebuild
system_api = { path = "system_api" }

[build-dependencies]
protoc-rust = "2"

[dev-dependencies]
tempfile = "3"

[workspace]
